### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by johndeere4344** [k4yt3x/LethalESP#1]
I am having issues with step 2, I dont have much experience with visual studio. How do I compile and adjust the properties and references?

**Comment by johndeere4344** [comment]
I tried using it without doing this method and it did not appear in-game.

**Comment by k4yt3x** [comment]
Did you install BepInEx for the game? Or r2modman?

**Comment by johndeere4344** [comment]
I use r2modman

**Comment by johndeere4344** [comment]
it shows up in the logs as loaded but nothing appears in-game

**Comment by k4yt3x** [comment]
Did you miss this instruction in the README:

> 4. Use F10, F11, and F12 to toggle enemy, map hazards, and loot ESP.

**Comment by johndeere4344** [comment]
No, I tried that many times and nothing showed up.

**Comment by k4yt3x** [comment]
I just downloaded the exact same file from GitHub and tried it, works fine for me. Not sure what's missing for you.

**Comment by k4yt3x** [comment]
With r2modman you should be able to just toss it into something like `%APPDATA%\r2modmanPlus-local\LethalCompany\profiles\Default\BepInEx\plugins` and that should be it.

**Comment by johndeere4344** [comment]
I dont know i've tried everything and nothings working

**Comment by k4yt3x** [comment]
Do you have another plugin that's conflicting with the keymap maybe?

**Comment by johndeere4344** [comment]
I thought that could've been an issue and removed all mods and it still didnt work, is there a specific screen setting for it to work? like windowed, fullscreen etc

**Comment by k4yt3x** [comment]
No, it should just...work. I've honestly got no clue what you're missing now.

**Comment by k4yt3x** [comment]
I'll leave you to figuring it out. This repo was meant to share how to code these kinds of stuff, not actually for normal people to download mods anyways.
